export default [
  {
    key: 'diken',
    name: 'Diken',
    url: 'http://www.diken.com.tr/feed',
    logo: require('../../assets/images/logos/diken.png'),
    backgroundColor: '#FDB42A',
  },
  {
    key: 'duvar',
    name: 'Duvar',
    url: 'https://www.gazeteduvar.com.tr/feed',
    logo: require('../../assets/images/logos/duvar.png'),
    backgroundColor: '#2e2e2e',
  },
  {
    key: 't24',
    name: 'T24',
    url: 'http://t24.com.tr/rss',
    logo: require('../../assets/images/logos/t24.png'),
    backgroundColor: '#0180C1',
  },
  {
    key: 'sol',
    name: 'soL',
    url: 'http://haber.sol.org.tr/rss/tumicerik',
    logo: require('../../assets/images/logos/sol.png'),
    backgroundColor: '#e7e7e7',
  },
  {
    key: 'karinca',
    name: 'Karınca',
    url: 'http://gazetekarinca.com/feed',
    logo: require('../../assets/images/logos/karinca.png'),
    backgroundColor: '#ff7f31',
  },
  {
    key: 'bianet',
    name: 'Bianet',
    url: 'http://bianet.org/bianet.rss',
    logo: require('../../assets/images/logos/bianet.png'),
    backgroundColor: '#FFF',
  },
  {
    key: 'evrensel',
    name: 'Evrensel',
    url: 'https://www.evrensel.net/rss/haber.xml',
    logo: require('../../assets/images/logos/evrensel.png'),
    backgroundColor: '#A41B1C',
  },
  {
    key: 'odatv',
    name: 'Oda TV',
    url: 'https://www.odatv.com/rss.php',
    logo: require('../../assets/images/logos/odatv.jpg'),
    backgroundColor: '#FFF',
  },
  {
    key: 'aktif',
    name: 'Aktif Haber',
    url: 'http://aktifhaber.com/rss/headlines',
    logo: require('../../assets/images/logos/aktif-haber.jpg'),
    backgroundColor: '#ffffff',
  },
  {
    key: 'yurt',
    name: 'Yurt Gazetesi',
    url: 'http://www.yurtgazetesi.com.tr/rss.php',
    logo: require('../../assets/images/logos/yurt.jpg'),
    backgroundColor: '#EE1C25',
  },
  {
    key: 'birgun',
    name: 'Birgün Gazetesi',
    url: 'https://www.birgun.net/feed',
    logo: require('../../assets/images/logos/birgun.png'),
    backgroundColor: '#FFF',
  },
  {
    key: 'sendika',
    name: 'Sendika.org',
    url: 'http://sendika63.org/feed/',
    logo: require('../../assets/images/logos/sendika.jpg'),
    backgroundColor: '#EF6F04',
  },
  {
    key: 'gercekgundem',
    name: 'Gerçek Gündem',
    url: 'https://www.gercekgundem.com/rss',
    logo: require('../../assets/images/logos/gercekgundem.png'),
    backgroundColor: '#FFF',
  },
  {
    key: 'cumhuriyet',
    name: 'Cumhuriyet Gazetesi',
    url: 'http://www.cumhuriyet.com.tr/rss/1.xml',
    logo: require('../../assets/images/logos/cumhuriyet.png'),
    backgroundColor: '#ffffff',
  },
  {
    key: 'bbc',
    name: 'BBC Türkçe',
    url: 'http://feeds.bbci.co.uk/turkce/rss.xml',
    logo: require('../../assets/images/logos/bbc.png'),
    backgroundColor: '#CC0101',
  },
  {
    key: 'acik',
    name: 'Açık Gazete',
    url: 'http://www.acikgazete.com/feed/',
    logo: require('../../assets/images/logos/acik.png'),
    backgroundColor: '#FFFFFF',
  },
  {
    key: 'dw',
    name: 'DW Türkçe',
    url: 'http://partner.dw.com/xml/rss-tur-all',
    logo: require('../../assets/images/logos/dw.png'),
    backgroundColor: '#FFF',
  },
  {
    key: 'sputnik',
    name: 'Sputnik Türkçe',
    url: 'https://tr.sputniknews.com/export/rss2/archive/index.xml',
    logo: require('../../assets/images/logos/sputnik.png'),
    backgroundColor: '#F6961D',
  },
]
